### ISSUE TITLE
Add redirect that removes the .html extension in API reference

### ISSUE THREAD

**Issue by kvelikov** [telerik/docs-seed#46]
Current behavior may harm google SEO score

**Comment by marin-bratanov** [comment]
Something like this can help if you are on ngnix https://github.com/telerik/blazor-docs/commit/203db2ecce0b1b32b591d7f5796d3ed4f92ce739#diff-ea9e52bc99620b455213e5f4ce4deca6

**Comment by marin-bratanov** [comment]
Which does not seem to work.

It is present in both Kendo and Blazor and while some initial tests indicated it worked in Kendo, it did break the Blazor API ([initial commit](https://github.com/telerik/kendo/commit/dd047f0af3373ff9f5226fb637644ad2b8440e09#diff-ffb94bd4e82efd8fe1936d4b3469613f)), and the [current commit](https://github.com/telerik/kendo/commit/06e9ce86b96fda5d31e49836f1fe063d45972648#diff-ffb94bd4e82efd8fe1936d4b3469613f) does not work in either it seems (maybe something else changed in the deployment environment after those commits because they seemed to work fine).

Applies to non-API ref content as well, and to docs hosted on both nginx and IIS.

**Comment by imtodor** [comment]
That behavior should be handled from the redirects in the corresponding server config file:

-	Web.config (IIS):
```
	        <rule name="Redirecting .html ext" enabled="true">
	          <match url="^(.*)[.]html$"/>
	          <conditions logicalGrouping="MatchAny">
	            <add input="{URL}" pattern="(.*)[.]html$"/>
	          </conditions>
	          <action type="Redirect" url="{ToLower:{R:1}}"/>
	        </rule>
```

- redirects.conf (nginx)

```
rewrite  ^/documentation/unite-ux/{{ redirect | remove_first: '/' }}$
         /documentation/unite-ux/{{ page.url | remove_first: '/' | replace: '.html', '' }}
         permanent;
```
